apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: myapp-replicaset-XX
  labels:
    app: myapp-XX
    type: front-end

spec:
  template:
    metadata: 
      name: myapp-pod-XX
      labels:
        app: myapp-XX
    spec:
      containers:
        - name: nginx-container
          image: nginx

  replicas: 3

  selector:
    matchLabels:
      app: myapp-XX